=== AbdullatifHabiba/Email-web-applicition/backend/emailweb/JsonSchema.JSON
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "DateOfBirth": {
      "type": "string"
    },
    "UserName": {
      "type": "string"
    },
    "Contacts": {
      "type": "object"
    },
    "Starred": {
      "type": "object"
    },
    "Trash": {
      "type": "object"
    },
    "Inbox": {
      "type": "object"
    },
    "Name": {
      "type": "string"
    },
    "Password": {
      "type": "string"
    },
    "Sent": {
      "type": "object"
    },
    "Drafts": {
      "type": "object"
    }
  },
  "required": [
    "DateOfBirth",
    "UserName",
    "Contacts",
    "Starred",
    "Trash",
    "Inbox",
    "Name",
    "Password",
    "Sent",
    "Drafts"
  ]
}

=== AbdullatifHabiba/Email-web-applicition/emailweb/logged.json
{"DateOfBirth":"١٦-٠٢-٢٠٠٦","UserName":"mohamed","Contacts":{},"Starred":{},"Trash":{},"Inbox":{},"Name":"Mohamed","Password":"00000000","Sent":{"Email1":{"Importance":1,"Object":"Hello","From":"mohamed","To":"ahmed","Body":"<p>How are U?<\/p>","Date":"٢٩-١٢-٢٠٢١ ٠٧:٠٦:٥٩"},"Email2":{"Importance":4,"Object":"Hello","From":"mohamed","To":"ahmed","Body":"<p>How are U?<\/p>","Date":"٢٩-١٢-٢٠٢١ ٠٧:٠٥:٥٤"}},"Drafts":{}}
